Assignment 1
services:
  ratings:
    build: .
    image: ghcr.io/parkcoco123/bookinfo-details:dev
    ports:
      - "8081:8081"
    environment:
      SERVICE_VERSION: v1

Assignment 2
services:
  ratings:
    build: .
    image: ghcr.io/parkcoco123/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      SERVICE_VERSION: v1

Assignment 3
services:
  productpage:
    build: .
    image: ghcr.io/parkcoco123/bookinfo-productpage:dev
    ports:
      - "8083:8083"
    environment:
      SERVICE_VERSION: v1

Assignment 4
services:
  ratings:
    build: ../ratings
    image: ghcr.io/parkcoco123/bookinfo-ratings:dev
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  details:
    build: ../sitkmutt-bookinfo-details
    image: ghcr.io/parkcoco123/bookinfo-details:dev
    ports:
      - "8081:8081"
    environment:
      ENABLE_EXTERNAL_BOOK_SERVICE: 'true'
      DO_NOT_ENCRYPT: 'false'
  mongodb:
    image: bitnami/mongodb:5.0.2-debian-10-r2
    volumes:
      - "./ratings/databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_USERNAME: ratings
      MONGODB_PASSWORD: CHANGEME
      MONGODB_DATABASE: ratings
  reviews:
    build: ../sitkmutt-bookinfo-reviews
    image: ghcr.io/parkcoco123/bookinfo-reviews:dev
    ports:
      - "8082:9080"
    environment:
      RATINGS_SERVICE: http://ratings:8080
  productpage:
    build: ../sitkmutt-bookinfo-productpage
    image: ghcr.io/parkcoco123/bookinfo-productpage:dev
    ports:
      - "8083:8083"
    environment:
      RATINGS_HOSTNAME: http://ratings:8080
      DETAILS_HOSTNAME: http://details:8081
      REVIEWS_HOSTNAME: http://reviews:9080
      FLOOD_FACTOR: 0